# Generated by Django 3.0.6 on 2020-06-15 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortenedlink',
            name='original_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='shortenedlink',
            name='shortened_link',
            field=models.URLField(blank=True),
        ),
    ]
